---
- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Tap Caskroom
      homebrew_tap: tap=homebrew/cask

    - name: Tap bundle
      homebrew_tap: tap=homebrew/bundle

    - name: Install and Update ansible
      homebrew:
        name: ansible
        state: latest

    - name: Install and Update mas
      homebrew:
        name: mas
        state: latest

    - name: Check dotfiles playbook
      stat:
        path: ~/dotfiles/playbook.yml
      register: dotfiles_playbook

    - name: Install dotfiles
      include_tasks: ~/dotfiles/playbook.yml
      when: dotfiles_playbook.stat.exists

    - name: Check brew bundle dump
      stat:
        path: ~/dotfiles/Brewfile
      register: dotfiles_Brewfile

    - name: Install OSX Apps from Brewfile https://github.com/Homebrew/homebrew-bundle
      command: brew bundle --file ~/dotfiles/Brewfile
      when: dotfiles_Brewfile.stat.exists
