---
- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Tap Caskroom
      homebrew_tap: tap=homebrew/cask

    - name: Tap bundle
      homebrew_tap: tap=homebrew/bundle

    - name: Install and Update ansible
      homebrew:
        name: ansible
        state: latest

    - name: Install and Update mas
      homebrew:
        name: mas
        state: latest

    - name: Check brew bundle dump
      stat:
        path: ~/dotfiles/osx/Brewfile
      register: dotfiles_Brewfile

    - name: Install OSX Apps from Brewfile https://github.com/Homebrew/homebrew-bundle
      command: brew bundle --file ~/dotfiles/osx/Brewfile
      args:
        chdir: ~/dotfiles/osx/
      when: dotfiles_Brewfile.stat.exists
      changed_when: ret.rc != 0

    - name: Check dotfiles playbook
      stat:
        path: ~/dotfiles/osx/playbook.yml
      register: dotfiles_playbook

    - name: Install dotfiles
      include_tasks: ~/dotfiles/osx/playbook.yml
      when: dotfiles_playbook.stat.exists

    - name: Check dotfiles Makefile
      stat:
        path: ~/dotfiles/Makefile
      register: dotfiles_Makefile

    - name: Install dotfiles by Makefile (if dotfiles_playbook not exists)
      make:
        chdir: ~/dotfiles/
        target: install
      when: 
        - not dotfiles_playbook.stat.exists
        - dotfiles_Makefile.stat.exists
