---
- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Check Sudo Password
      command: ls
      become: yes
      become_method: sudo

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Tap Caskroom
      homebrew_tap: tap=homebrew/cask

    - name: Tap bundle
      homebrew_tap: tap=homebrew/bundle

    - name: Install mas
      homebrew:
        name: mas
        state: latest
